name: Sync pyproject.toml

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      module:
        description: The name of the module
        type: string
        required: true
      path:
        description: The working directory (must contain pyproject.toml)
        type: string
        required: true
      version:
        description: The version to pass to set in pyproject.toml
        type: string
        default: ""
      head:
        description: The branch or tag to checkout
        type: string
        required: true

jobs:
  sync-pyproject:
    name: Sync pyproject.toml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ inputs.head }}
      - uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b
      - name: uv-version
        run: uvx --from=toml-cli toml set --toml-path=${{ inputs.path }}/pyproject.toml project.version ${{ inputs.version }}
      - name: uv-lock
        run: |
          uv export --package cellophane-${{ inputs.module }} --no-dev --no-hashes > ${{ inputs.path }}/requirements.lock
          uv export --package cellophane-${{ inputs.module }} --no-hashes > ${{ inputs.path }}/requirements-dev.lock
      - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
        with:
          name: ${{ inputs.module }}-meta
          path: |
            ${{ inputs.path }}/pyproject.toml
            ${{ inputs.path }}/requirements.lock
            ${{ inputs.path }}/requirements-dev.lock
          retention-days: 1
