---
name: PR Close
permissions: read-all

on: # yamllint disable-line rule:truthy
  pull_request_target:
    types: [closed]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}

jobs:
  metadata:
    if: (!github.event.act && startsWith(github.head_ref, 'release/') && github.event.pull_request.merged)
    name: Cellect PR metadata
    runs-on: ubuntu-latest
    outputs:
      module: ${{ steps.metadata.outputs.module }}
      path: ${{ steps.metadata.outputs.path }}
      tag: ${{ steps.metadata.outputs.tag }}
    steps:
      - name: metadata
        id: metadata
        env:
          BODY: ${{ github.event.pull_request.body }}
        run: |
          for field in module path tag; do
            sed -nE 's/.*<!-- ('${field}'="[^"]+") -->.*/\1/p' <<< "$BODY" | tr -d '"' | tee -a "$GITHUB_OUTPUT"
          done

  publish-tag:
    name: Publish Tag
    runs-on: ubuntu-latest
    if: (!github.event.act && github.event.pull_request.merged)
    needs: metadata
    permissions:
      contents: write
    env:
      next_tag: ${{ needs.metadata.outputs.tag }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: tag
        run: |
          git tag ${{ env.next_tag }}
          git push origin ${{ env.next_tag }} -f